version: "3.8"
volumes:
  php-fpm-socket:
  pma-session-store:
  db-store:
  vendor-store:
  node_modules-store:
services:
  # app:
  #   build: ./infra/docker/php
  #   volumes:
  #     - php-fpm-socket:/var/run/php-fpm
  #     - ./backend:/work/backend
  #     - vendor-store:/work/backend/vendor
  #   depends_on:
  #     - db

  # web:
  #   build: ./infra/docker/nginx
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - php-fpm-socket:/var/run/php-fpm
  #     - ./backend:/work/backend
  #     - node_modules-store:/work/backend/node_modules

  db:
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

  cs:
    image: herloct/php-cs-fixer
    volumes:
      - ./backend:/project

  pma:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - pma-session-store:/sessions
    depends_on:
      - db
